image: keremkayabay/sphinx:latest

tasks:
  - init: make

vscode:
  extensions:
    - ms-python.python@2020.10.332292344:5ctthQ25Qni5/aAuOIUTYQ==
    - lextudio.restructuredtext@145.0.0:wH2lqCSEh5t5V7WXDBFUcA==